jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
      - name: Prepare actions
        uses: ./.github/actions/prepare
      - name: Formatting
        run: yarn fmt:check
      - uses: mshick/add-pr-comment@v2
        if: failure()
        with:
          message-failure: |
            Uh oh! The formatting checks found some issues. Please run `yarn fix` and commit the changes.

name: Formatting

on:
  pull_request: ~
  merge_group: ~

  push:
    branches:
      - main
