jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
      - name: Prepare actions
        uses: ./.github/actions/prepare
      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3
      - name: Sync astro
        run: doppler run -- yarn astro sync
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
      - name: Unit tests
        run: yarn test
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
      - uses: mshick/add-pr-comment@v2
        if: failure()
        with:
          message-failure: |
            Uh oh! Tests failed. Run `yarn test` locally to reproduce.

name: Test

on:
  pull_request: ~
  merge_group: ~

  push:
    branches:
      - main
